<header>
        <h1>Psípotřeby.cz</h1>
        <h3>To nejlepší pro vaše čtyřnohé miláčky.</h3>
</header>


<nav>
    <ul>
        <li>O nás</li>
        <li>Hračky</li>
        <li>Vodítka</li>
        <li>Krmivo</li>
        <li>Pelíšky</li>
        <li>Kontakt</li>
    </ul>
</nav>

<footer>
    <p>Copyright (C) 2012 PsiPotreby.cz, Jan Novák</p>
    <p>Copyright (C) 2012 PsiPotreby.cz, Jan Novák</p>
    <p>Copyright (C) 2012 PsiPotreby.cz, Jan Novák</p>
    <p>Copyright (C) 2012 PsiPotreby.cz, Jan Novák</p>
    <p>Copyright (C) 2012 PsiPotreby.cz, Jan Novák</p>
    <p>Copyright (C) 2012 PsiPotreby.cz, Jan Novák</p>
</footer>



<h1>Podobné produkty:</h1>
<ul>
    <li>Psí tyčinka Multivitamin</li>
    <li>Vitamíny pro psy</li>
    <li>Doplňky stravy</li>
</ul>

<h1>Akční nabídky:</h1>
<ul>
    <li>Vodítko Denny</li>
    <li>...</li>
</ul>